<!doctype html>
<html lang="en">

    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
        <meta http-equiv="X-UA-Compatible" content="ie=edge">
        <title>Spring Boot FreeMarker Template</title>
    </head>

    <body>
        <h1>Freemarker Template</h1>
        Greetings, ${username}. Your password is: <b>${password}</b>
        <br/>
        The music you like is Metal: ${metal}
    </body>

</html>